openapi: 3.0.3
info:
  title: Thing Model Catalog - OpenAPI 3.0
  version: 0.0.1
externalDocs:
  description: Find out more about Thing Model Catalog
  url: https://github.com/web-of-things-open-source/tm-catalog-cli
servers:
  - url: ''
tags:
  - name: inventory
    description: Access to the inventory of the catalog
  - name: thing-models
    description: Access to Thing Model content
paths:
  /inventory:
    get:
      tags:
        - inventory
      summary: Get the inventory of the catalog
      description: Returns the catalogs inventory
      operationId: getInventory
      parameters:
        - name: filter[author]
          in: query
          description: Filters the inventory by one or more authors. The filter works additive to other filters.
          schema:
            type: string
          example: filter[author]=MyCompany,YourCompany
        - name: filter[manufacturer]
          in: query
          description: Filters the inventory by one or more manufacturers. The filter works additive to other filters.
          schema:
            type: string
          example: filter[manufacturer]=abb,danfoss
        - name: filter[mpn]
          in: query
          description: Filters the inventory by one ore more mpn (manufacturer part number). The filter works additive to other filters.
          schema:
            type: string
          example: filter[mpn]=B21,FC102
        - name: filter[original]
          in: query
          description: Filters the inventory by one or more original ID of a Thing Model. The filter works additive to other filters.
          schema:
            type: string
          example: filter[original]=12345
        - name: search[content]
          in: query
          description: >-
            Filters the inventory by content search with the help of an awesome query
            language
          schema:
            type: string
        - name: sort
          in: query
          description: >-
            Sorts the inventory by one or more fields. The sort is applied in the order of the fields. 
            The sorting is done ascending per field by default. If a field needs to be sorted descending,
            prefix it with a HYPHEN-MINUS "-")
          schema:
            type: string
            enum: [author, manufacturer, mpn]
          example: sort=author,-manufacturer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryResponse'
              examples:
                inventory:
                  $ref: '#/components/examples/InventoryExample'
        '400':
          description: Invalid filter parameter supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
  /inventory/{inventoryId}:
    get:
      tags:
        - inventory
      summary: Get an inventory entry by inventory ID
      description: Returns a single inventory entry
      operationId: getInventoryById
      parameters:
        - name: inventoryId
          in: path
          description: ID of the inventory entry
          required: true
          schema:
            type: string
          example: mycompany/abb/B21
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryEntryResponse'
              examples:
                inventoryEntry:
                  $ref: '#/components/examples/InventoryEntryExample'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Inventory entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
  /inventory/{inventoryId}/versions:
    get:
      tags:
        - inventory
      summary: Get the versions of an inventory entry
      description: Returns the versions of an inventory entry by it`s ID
      operationId: getInventoryVersionsById
      parameters:
        - name: inventoryId
          in: path
          description: ID of the inventory entry
          required: true
          schema:
            type: string
          example: mycompany/abb/B21
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryEntryVersionsResponse'
              examples:
                versionsExample:
                  $ref: '#/components/examples/InventoryEntryVersionsExample'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Inventory entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
  /thing-models/{tmId}:
    get:
      tags:
        - thing-models
      summary: Get the content of a Thing Model by it's ID
      description: Returns the actual content of a Thing Model
      operationId: getThingModelById
      parameters:
        - name: tmId
          in: path
          description: ID of the Thing Model
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
              example: the Thingmodel as JSON
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Content of the Thing Model not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
components:
  schemas:
    Inventory:
      required:
        - meta
        - contents
      type: object
      properties:
        meta:
          required:
            - created
          type: object
          properties:
            created:
              type: string
              format: date-time
              example: '2023-11-16T11:06:18.8213578+01:00'
        contents:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InventoryEntry'
    InventoryEntry:
      required:
        - schema:author
        - schema:manufacturer
        - schema:mpn
        - versions
      type: object
      properties:
        schema:author:
          $ref: '#/components/schemas/SchemaAuthor'
        schema:manufacturer:
          $ref: '#/components/schemas/SchemaManufacturer'
        schema:mpn:
          type: string
          example: B21
        versions:
          type: array
          items:
            $ref: '#/components/schemas/InventoryEntryVersion'
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    InventoryEntryVersion:
      required:
        - tmId
        - original
        - description
        - version
      type: object
      properties:
        tmId:
          type: string
          example: mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
        original:
          type: string
          example: e7f19370-84a3-11ee-b962-0242ac120002
        description:
          type: string
          example: Some description of the thing
        version:
          $ref: '#/components/schemas/ModelVersion'
        timestamp:
          type: string
          example: 20231116091345
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
      example: >-
        /thing-models/mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
    InventoryResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/Inventory'
    InventoryEntryResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/InventoryEntry'
    InventoryEntryVersionsResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InventoryEntryVersion'
    SchemaAuthor:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: MyCompany
    SchemaManufacturer:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: ABB
    Link:
      type: object
      required:
        - rel
        - href
      properties:
        rel:
          type: string
          enum:
            - content
            - self
        href:
          type: string
    ModelVersion:
      required:
        - model
      type: object
      properties:
        model:
          type: string
          example: 1.0.1
    ErrorResponse:
      required:
        - title
        - status
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
        status:
          type: integer
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  examples:
    InventoryEntryVersionsExample:
      value:
        data:
          - tmId: mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
            original: e7f19370-84a3-11ee-b962-0242ac120002
            description: Some new description of the device
            timestamp: 20231116091345
            version:
              model: 1.0.1
            links:
              - rel: content
                href: /thing-models/mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
          - tmId: mycompany/abb/B21/v1.0.0-20231017080730-4832ab7bbeac.tm.json
            original: e7f19370-84a3-11ee-b962-0242ac120002
            description: Some description of the device
            timestamp: 20231017080730
            version:
              model: 1.0.0
            links:
              - rel: content
                href: /thing-models/mycompany/abb/B21/v1.0.0-20231017080730-4832ab7bbeac.tm.json
          - tmId: mycompany/abb/B21/v1.0.0-20231015102132-6391fe4bcefc.tm.json
            original: e7f19370-84a3-11ee-b962-0242ac120002
            description: Some description of the device
            timestamp: 20231015102132
            version:
              model: 1.0.0
            links:
              - rel: content
                href: /thing-models/mycompany/abb/B21/v1.0.0-20231015102132-6391fe4bcefc.tm.json
    InventoryEntryExample:
      value:
        data:
          schema:author:
            name: MyCompany
          schema:manufacturer:
            name: ABB
          schema:mpn: B21
          versions:
            - tmId: mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
              original: e7f19370-84a3-11ee-b962-0242ac120002
              description: Some new description of the device
              timestamp: 20231116091345
              version:
                model: 1.0.1
              links:
                - rel: content
                  href: /thing-models/mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
            - tmId: mycompany/abb/B21/v1.0.0-20231017080730-4832ab7bbeac.tm.json
              original: e7f19370-84a3-11ee-b962-0242ac120002
              description: Some description of the device
              timestamp: 20231017080730
              version:
                model: 1.0.0
              links:
                - rel: content
                  href: /thing-models/mycompany/abb/B21/v1.0.0-20231017080730-4832ab7bbeac.tm.json
            - tmId: mycompany/abb/B21/v1.0.0-20231015102132-6391fe4bcefc.tm.json
              original: e7f19370-84a3-11ee-b962-0242ac120002
              description: Some description of the device
              timestamp: 20231015102132
              version:
                model: 1.0.0
              links:
                - rel: content
                  href: /thing-models/mycompany/abb/B21/v1.0.0-20231015102132-6391fe4bcefc.tm.json
          links:
            - rel: self
              href: /inventory/mycompany/abb/B21
    InventoryExample:
      value:
        data:
          contents:
            meta:
              created: "2023-11-16T18:07:18.8213578+01:00"
            mycompany/abb/B21:
              schema:author:
                name: MyCompany
              schema:manufacturer:
                name: ABB
              schema:mpn: B21
              versions:
                - tmId: mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
                  original: e7f19370-84a3-11ee-b962-0242ac120002
                  description: Some new description of the device
                  timestamp: 20231116091345
                  version:
                    model: 1.0.1
                  links:
                    - rel: content
                      href: /thing-models/mycompany/abb/B21/v1.0.1-20231116091345-7256fc6baeec.tm.json
                - tmId: mycompany/abb/B21/v1.0.0-20231017080730-4832ab7bbeac.tm.json
                  original: e7f19370-84a3-11ee-b962-0242ac120002
                  description: Some description of the device
                  timestamp: 20231017080730
                  version:
                    model: 1.0.0
                  links:
                    - rel: content
                      href: /thing-models/mycompany/abb/B21/v1.0.0-20231017080730-4832ab7bbeac.tm.json
              links:
                - rel: self
                  href: /inventory/mycompany/abb/B21
            yourcompany/danfoss/FC102:
              schema:author:
                name: YourCompany
              schema:manufacturer:
                name: Danfoss
              schema:mpn: FC 102
              versions:
                - tmId: yourcompany/danfoss/FC102/v1.0.0-20230821121030-2522cf7bbead.tm.json
                  original: danfoss-kxf19370
                  description: Some description of the device
                  timestamp: 2023082112103
                  version:
                    model: 1.0.0
                  links:
                    - rel: content
                      href: /thing-models/yourcompany/danfoss/FC102/v1.0.0-20230821121030-2522cf7bbead.tm.json
              links:
                - rel: self
                  href: /inventory/yourcompany/danfoss/FC102
